//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_PM02_Koshenskiy.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int accounting_id { get; set; }
        public int request_id { get; set; }
        public System.DateTime date_reception { get; set; }
        public Nullable<int> priority_id { get; set; }
        public Nullable<int> wizard_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<decimal> repair_price { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual Request Request { get; set; }
        public virtual Status Status { get; set; }
        public virtual Wizard Wizard { get; set; }
    }
}
