//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_PM02_Koshenskiy.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Accounting = new HashSet<Accounting>();
        }
    
        public int request_id { get; set; }
        public int client_id { get; set; }
        public int type_equipment { get; set; }
        public string serial_number { get; set; }
        public string problem_description { get; set; }
        public string type_malfunction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting> Accounting { get; set; }
        public virtual Client Client { get; set; }
        public virtual Type_equipment Type_equipment1 { get; set; }
    }
}
